server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountsdb
    username: postgres
    password: postgres
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true
  security.oauth2.resourceserver:
    jwt:
      issuer-uri: http://localhost:8060/realms/finobank
      jwk-set-uri: http://localhost:8060/realms/finobank/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Finobank Accounts Application"
    version: "1.0.0"