server:
  port: 8072

spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8060/realms/finobank
          jwk-set-uri: http://localhost:8060/realms/finobank/protocol/openid-connect/certs

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8070/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      gateway:
        enabled: true
    info:
      env:
        enabled: true

info:
  app:
    name: "gatewayserver"
    description: "Finobank Gateway Server Application"
    version: "1.0.0"