server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/paymentsdb
    username: postgres
    password: postgres
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "payments"
    description: "Finobank Payments Application"
    version: "1.0.0"