spring:
  datasource:
    url: jdbc:postgresql://usersdb:5432/usersdb
    username: postgres
    password: postgres
  security.oauth2.resourceserver:
    jwt:
      issuer-uri: http://localhost:8060/realms/finobank
      jwk-set-uri: http://keycloak:8060/realms/finobank/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/