spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/usersdb
    username: postgres
    password: postgres
  flyway:
    locations: classpath:/db
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "users"
    description: "Finobank Users Application"
    version: "1.0.0"